[package]
name = "amalgamator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", optional = true }

[features]
serde = ["dep:serde"]

[dev-dependencies]
serde_json = "1"
serde = { version = "1",  features = ["derive"] }   